apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicetesting-deployment
  labels:
    app: servicetesting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicetesting
  template:
    metadata:
      labels:
        app: servicetesting
    spec:
      containers:
      - name: servicetesting
        image: sal2apao/servicetesting:0.0.2-alpine
        #image: nginx:latest
        ports:
        - containerPort: 1323
        volumeMounts:
        - name: config-vol
          mountPath: /config
        env:
        #Define the environment variable
        #- name: HOST
        #  value: "https://httpbin.org"
        #- name: PORT
        #  value: ""
        #- name: URI
        #  value: "/status"
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: HOST
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: PORT
        - name: URI
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: URI
      restartPolicy: Always
      volumes:
      - name: config-vol
        configMap:
          name: appconfig